#+OPTIONS: toc:nil
#+BEGIN_EXPORT html
---
layout: default
title: How to use Docker for personal projects
subtitle: Using docker containers to improve local software development
---
#+END_EXPORT
#+TOC: headlines 2

* Why You Need Docker in Your Personal Projects
If you're anything like me, your computer is filled with dozens of personal projects in varying states of disrepair.

I have no idea how to even run them, let alone compile them. I don't know what state they're in and I can't remember how to use the language they're written. Their library dependencies have been overwritten or removed -- or were never on my current machine to begin with.

Using Docker as the starting point for your personal applications will make it easier for you to return to them later. And, if your application turns into something real, you've already got the benefits of containerized, deploying applications built in. Lastly, if you ever upgrade machines, having your personal work in containers means zero-setup-required on the new machine (except downloading Docker).

Incorporating Docker early and often can enable your workflows to increase long term efficiency, and it's a great skill to bring to a future employer.

* Docker in 2 Minutes
** What is Docker?
Docker solves the problem of telling your stakeholder "Well, it worked on my machine." after the software you delivered fails epicly. It does this by providing "containers" for your code, similiar to a virtual machine or virtual environment. The container is isolated from the machine it runs on, and includes everything required to allow an application to run, including it's own Operating System. The container can therefore be packaged up and deployed with minimal compatibility issues.

** Why do we use it?
Because of the isolated environment, your workflow is simplified. No more issues around running multiple versions of the same dependency, no more shipping code only to discover the destination code is built on a different OS. No more forgetting your commands to compile and run your code after leaving it untouched for months. It's all baked in. The entire lifecycle is simplified by containers, all the way through to production deployment.

* Tutorial: Docker for personal projects
Something funny happened when I wrote this blog post. I dusted off an old containerized application to put my money where my mouth is. It's an application I haven't touched in about 6 months, and frankly have no idea where I left off. The premise was simple: make millions with a high-frequency trading bot, and learn C++ at the same time. I ended up writing a few interesting abstractions on HTTP Requests to fetch the current price of cryptocurrencies from [[https://www.alphavantage.co/][AlphaVantage]].

Anyway, being the "Do Future You a Favor" engineer I am, I even wrote a little README for this moment:

#+begin_src
# From README.md:

# HFT
High Frequency Trading is the best way to make money.

#Local Development

# To build the docker container:
docker build . -t cpp-build-base:0.1.0

# profit:
docker run --rm -it cpp-build-base:0.1.0
#+end_src

Unlike every other time I've gone back to a personal project (and abandoned it), this one worked. I built the container and ran it. The code even still works! It did take a LONG time for the container build, since the ubunto base image had some major updates, but look at that! My high-frequency-trading firm is already prioritizing security by keeping its base images up to date!

I can't describe the number of times I've returned to a half-finished personal project and thought, I don't even know how to start it up and run it any more. Do yourself a favor, and leave it to Docker.

Let's see how in the next section.

** Language: CPP

Some key vocabulary up front. Docker Images vs Docker Containers. We build images, and run containers.

Images are built via ~docker build~, and then they're run as containers with ~docker run~. Building the image is like writing a recipe for a new computer. The image will contain an operating system first and foremost. Then we'll install any additional software we need, and copy our application on to "the computer". We finally tell Docker how to run the image. But the key is that, the image doesn't run yet. These recipes--our completed images--are what gets past around and makes this all so convenient.

Docker run takes little know-how: fetch our image (they get uploaded to some repo when they're built), and execute it. Some may be long running, others may be short-lived (like my HFT).

~docker build~ is responsible for assembling our container. This is where we're going to spin up the isolated virtual environment that will run our code. We do this by writing a Dockerfile, and running the build command to follow the instructions therein. It's important to note that nothing will actually run at this time. The end result is that the image is built and uploaded to the cloud for future use.

#+begin_src -n
FROM ubuntu:bionic

RUN apt-get update && \
	apt-get install -y build-essential git cmake autoconf libtool pkg-config libcurl4-openssl-dev libjsoncpp-dev

WORKDIR /src

COPY CMakeLists.txt main.cpp ./

RUN cmake . && make

CMD ["./HFT"]
#+end_src

What's going on with this Dockerfile specifically? Let's dive in. The first line is our base image, ~ubunto:bionic~. This means we have a clean linux OS running on our "machine". These can be edited, but generally, it's not going to have very much bloat on it.

The next line is to bring our software up to date. apt-get update runs the security patches I mentioned by grabbing the latest versions of all those packages from the cloud, and installing them into our container.

the ~&& \ apt=get install -y...~ command is for cpp specifically. This cmmand installs the libraries we need to run our code, just the way packages are installed on any other local machine.

Next, we update the "working directory" of our container with ~WORKDIR /src~. This is necessary for the commands which follow, so that those commands are carried out in the right place. In this case, we're telling Docker, the magic happens in /src.

Then, we load our beautifully written code on to the container. Quite simply, we copy it from the local destination into the container. The destination is ./ -- the top level of our working directory.

After that, we run a common cpp command to compile our project! We would do this same exact thing if we were building and running locally, too. In this case, we need to tell the container, compile my package! In this project, it's with a make file. Boy am I glad I didn't try to remember this! Like I said, I would never have been able to make this run again.

In the last step of build time, we need to tell Docker what to do when this image is run as a container. In this case, when we've told Docker, execute the shell command, ~./HFT~ which like any old execution command.

Now, we can run our image with ~docker run --rm -it cpp-build-base:0.1.0~.

Here's the output!

#+begin_src
maxfrey@Maxs-Mac-mini containerized % docker run --rm -it cpp-build-base:0.1.0
https://www.alphavantage.co/query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey=MBNOFOZHP0KT13HIhttps://www.alphavantage.co/query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=USD&apikey=MBNOFOZHP0KT13HI
Got 439 bytes at write_callback
Chunk Memory:
{
    "Realtime Currency Exchange Rate": {
        "1. From_Currency Code": "BTC",
        "2. From_Currency Name": "Bitcoin",
        "3. To_Currency Code": "USD",
        "4. To_Currency Name": "United States Dollar",
        "5. Exchange Rate": "26500.99000000",
        "6. Last Refreshed": "2023-06-17 19:13:01",
        "7. Time Zone": "UTC",
        "8. Bid Price": "26500.98000000",
        "9. Ask Price": "26500.99000000"
    }
}
From Currency: BTC
To Currency: USD
Exchange Rate: 26500.99000000
#+end_src


What did this just do? Well, it ran my program of course! It fetched the current price of Bitcoin in USD of course -- 6 months after I wrote this code and forgot everything I ever knew about cpp.

That's why you should put in the effort to Dockerize your work, even if it's for personal use.

These are the favors you can do yourself that save you time and will enable you to build lots of half-finished projects that at least you'll be able to run in the future. 


* Common Commands and Documentation
[[https://docs.docker.com/engine/reference/builder/][Dockerfile documentation]]
